### ISSUE TITLE
Please make an option to hide the area where the tabs and the gear icon are located

### ISSUE THREAD

**Issue by dlazycoder** [thatmounaim/multineuz#1]
Please make an option to hide the area where the tabs and the gear icon are located as it takes space and reducts the gaming experience.

**Comment by thatmounaim** [comment]
Sorry for the delay, i am currently on a break and i just happened to see this.

Planning to do a full rewrite of the project soon , i will take your feedback into the next version.

**Comment by thatmounaim** [comment]
@dlazycoder 
Check https://github.com/thatmounaim/multineuz/releases/tag/v1.0.4
